export { default as Header } from './Header'
export { default as FeaturesGrid } from './FeaturesGrid'
export { default as Hero } from './Hero'
export { default as PopularNFTs } from './PopularNFTs'
export { default as RoadMap } from './RoadMap'
export { default as FAQ } from './FAQ'